version: "3"
services:
  main:
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      GO_ENV: development
    volumes:
      - ".:/usr/src/app"
    depends_on:
      - "db"
  ngrok:
    image: wernight/ngrok
    env_file: .ngrok.env
    environment:
      NGROK_PORT: main:3000
    ports:
      - "3001:4040"
    depends_on:
      - "main"
  db:
    image: mongo
    volumes:
      - "db_volume:/data/db"
    ports:
      - "3003:27017"
  mongo-express:
    image: mongo-express
    ports:
      - "3002:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: db
    depends_on:
      - "db"
volumes:
  db_volume:
